# Generated by Django 2.1.7 on 2019-12-25 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('category_fit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not sure', 'Not Sure')], max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('relevant_feedback', models.TextField(blank=True)),
                ('category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
