# Generated by Django 2.1.7 on 2019-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190306_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
