# Generated by Django 2.1.7 on 2019-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(upload_to='blog_images'),
        ),
    ]
