# Generated by Django 2.1.7 on 2019-03-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
