# Generated by Django 2.1.7 on 2019-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190307_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Brain Research Tagging News', 'Brain Research Tagging News'), ('Brain Health News', 'Brain Health News'), ('Research Domain Criteria News', 'Research Domain Criteria News')], default='Default', max_length=100),
        ),
    ]
