# Generated by Django 2.1.7 on 2019-03-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='replies', to='blog.CommentModel'),
        ),
    ]
