# Generated by Django 2.1.7 on 2019-03-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190310_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='content',
        ),
    ]
